name: CD # 원하는 이름으로!

on:
  push:
    branches:
      - main # action 트리거 브랜치

jobs:
  build:
    runs-on: ubuntu-latest # action 스크립트가 작동될 OS

    steps: # 작업 단계
      # 기본 actions
      - name: Checkout source code # 단계별 이름, 구분자로 소스를 가져옴
        uses: actions/checkout@v2

      - name: Set up JDK 11 # JDK 설치 JAVA 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: make application.yaml
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./application.yaml
          echo "${{ secrets.APPLICATION }}" > ./application.yaml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash


      - name: Get current time # Versioning을 위해 사용
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Generate deployment package
        # Procfile : Beanstalk 작업 이해할 수 있게 만들어주는 파일
        run: |
          mkdir deploy
          cp build/libs/fouthSeminar-0.0.1-SNAPSHOT.jar deploy/sopt-seminar-prod-ebextensions-1.jar
          cp Procfile deploy/Procfile 
          cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r sopt-seminar-prod-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}} .

      - name: Deploy Consumer to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with: # 해당 job에 필요한 변수들 등록
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: sopt-seminar
          environment_name: Sopt-seminar-env
          version_label: sopt-seminar-prod-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}
          region: ap-northeast-2
          deployment_package: deploy/sopt-seminar-prod-label-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip